apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: safepipeline-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: safepipeline.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: safepipeline-service
                port:
                  number: 80
